import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/react"

const poppins = Poppins({weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] ,subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <html lang="en">
      <body className={[poppins.className, "bg-black", "text-white"].join(" ")}>{children}</body>
      <svg className="fixed left-0 bottom-0 w-full z-[-1] opacity-40" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#0099ff" d="M0,64L15,106.7C30,149,60,235,90,261.3C120,288,150,256,180,218.7C210,181,240,139,270,133.3C300,128,330,160,360,192C390,224,420,256,450,250.7C480,245,510,203,540,192C570,181,600,203,630,202.7C660,203,690,181,720,154.7C750,128,780,96,810,96C840,96,870,128,900,154.7C930,181,960,203,990,224C1020,245,1050,267,1080,272C1110,277,1140,267,1170,234.7C1200,203,1230,149,1260,144C1290,139,1320,181,1350,202.7C1380,224,1410,224,1425,224L1440,224L1440,320L1425,320C1410,320,1380,320,1350,320C1320,320,1290,320,1260,320C1230,320,1200,320,1170,320C1140,320,1110,320,1080,320C1050,320,1020,320,990,320C960,320,930,320,900,320C870,320,840,320,810,320C780,320,750,320,720,320C690,320,660,320,630,320C600,320,570,320,540,320C510,320,480,320,450,320C420,320,390,320,360,320C330,320,300,320,270,320C240,320,210,320,180,320C150,320,120,320,90,320C60,320,30,320,15,320L0,320Z"></path></svg>
    </html>
    </>
  );
}
